# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 12:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_item', models.CharField(max_length=150)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Item',
            },
        ),
        migrations.CreateModel(
            name='pesos_grupos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(choices=[('Aliemntacao_e_bebidas', 'Aliemntacao_e_bebidas'), ('Habitacao', 'Habitacao'), ('Artigos_e_residencia', 'Artigos_e_residencia'), ('Vestuario', 'Vestuario'), ('Transportes', 'Transportes'), ('Saude_e_cuidados_especiais', 'Saude_e_cuidados_especiais'), ('Despesas_pessoais', 'Despesas_pessoais'), ('Educacao', 'Educacao'), ('Comunicacao', 'Comunicao')], max_length=150)),
                ('peso', models.FloatField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pesos grupos',
            },
        ),
        migrations.CreateModel(
            name='subgrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_subgrupo', models.CharField(max_length=150)),
                ('peso_subgrupo', models.FloatField(verbose_name='peso do subgrupo')),
                ('grupo_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipc_novo_app.pesos_grupos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Subgrupos',
            },
        ),
        migrations.CreateModel(
            name='subitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_subitem', models.CharField(max_length=150)),
                ('peso_subitem', models.FloatField(verbose_name='peso do subitem')),
                ('item_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipc_novo_app.item')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Subitem',
            },
        ),
    ]
