# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipc_novo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='pesos_grupos',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='subgrupo',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='subitem',
            name='usuario',
        ),
    ]
